### ISSUE TITLE
Getting rid of duplicated files, as the originals are now upstream

### ISSUE THREAD

**Issue by NikolajSchlej** [flathub/com.github.LongSoft.UEFITool#1]
@vulpes2, looks like this repo has files that upstream also has now, and I think we should certainly remove the duplicates, but I do not know how to make it without breaking FlatHub builds. 
Could you make a PR?

**Comment by vulpes2** [comment]
Absolutely, I was meant to do that this weekend as I've been quite busy lately. I'll update the manifest later this week.

**Comment by vulpes2** [comment]
Addressed in #3
